# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82601caaeb85255838e0f5866230bc101ca53552b6996a63e672cad4d4ac746236caae3799c37d1b6437e862c5b6ce7191c3bd1afbfca3a0f778a7ea2c098092

test:
  secret_key_base: 66fed7cfea5c1969a3d82cfdb9b13617dce77d3ce730e9c4899a3d5fa47d0e3dab3f9453d785a9e11a219535e8ac7e11ebff8b663768cf44c34a98c0e4cdc9f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
